public enum commandType {LOGIN, LOGOUT, TRANSACTION, FREEZE_ACCOUNT, UNFREEZE_ACCOUNT, CREATE_CUSTOMER, 
						DELETE_CUSTOMER, LOOKUP_CUSTOMER, OPEN_CREDIT_LINE, CLOSE_ACCOUNT,
						VIEW_LOGS, UNDEFINED}
